
RADIATION_STRENGTH = 100
NUMBER_OF_MOVES_PER_MOVE_LIST = 3
NUMBER_OF_FEATURES_PER_MOVE = 1
DEBUG = True

MOVE_FEATURE_CHANGE_RATE = 4 # 1 in MOVE_FEATURE_CHANGE_RATE of changing

IDEAL_TURNS = 15
IDEAL_TURNS_TOLERANCE = 5